// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Select3
Rcpp::List Select3(const arma::mat& dat1, const arma::mat& dat2, const arma::mat& dat3, const int n, const arma::mat& all_models);
RcppExport SEXP _SingleCln_Select3(SEXP dat1SEXP, SEXP dat2SEXP, SEXP dat3SEXP, SEXP nSEXP, SEXP all_modelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dat1(dat1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dat2(dat2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dat3(dat3SEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type all_models(all_modelsSEXP);
    rcpp_result_gen = Rcpp::wrap(Select3(dat1, dat2, dat3, n, all_models));
    return rcpp_result_gen;
END_RCPP
}
// indptSTM_cpp3
Rcpp::List indptSTM_cpp3(const arma::mat& dat1, const arma::mat& dat2, const arma::mat& dat3, const int n);
RcppExport SEXP _SingleCln_indptSTM_cpp3(SEXP dat1SEXP, SEXP dat2SEXP, SEXP dat3SEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type dat1(dat1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dat2(dat2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type dat3(dat3SEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(indptSTM_cpp3(dat1, dat2, dat3, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SingleCln_Select3", (DL_FUNC) &_SingleCln_Select3, 5},
    {"_SingleCln_indptSTM_cpp3", (DL_FUNC) &_SingleCln_indptSTM_cpp3, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SingleCln(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
