# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Select3 <- function(dat1, dat2, dat3, n, all_models) {
    .Call(`_SingleCln_Select3`, dat1, dat2, dat3, n, all_models)
}

indptSTM_cpp3 <- function(dat1, dat2, dat3, n) {
    .Call(`_SingleCln_indptSTM_cpp3`, dat1, dat2, dat3, n)
}

